In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
#1 data frame
df = pd.DataFrame([11,22,23,])
print(df)

    0
0  11
1  22
2  23

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
data = {
    'name':['rajesh','ansh','suraj','ankit'],
    'age':[22,23,24,25],
    'roll no':[22,33,44,55]

}

In [ ]:
df=pd.DataFrame(data)
print(df)

     name  age  roll no
0  rajesh   22       22
1    ansh   23       33
2   suraj   24       44
3   ankit   25       55

In [ ]:
# 2 basic dataframe understanding

In [ ]:
df.head(2) # top rows

     name  age  roll no
0  rajesh   22       22
1    ansh   23       33

In [ ]:
df.tail(2)

    name  age  roll no
2  suraj   24       44
3  ankit   25       55

In [ ]:
df.shape

(4, 3)

In [ ]:
df.columns

Index(['name', 'age', 'roll no'], dtype='object')

In [ ]:
df.rename(columns={'roll no':'reg'})

     name  age  reg
0  rajesh   22   22
1    ansh   23   33
2   suraj   24   44
3   ankit   25   55

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     4 non-null      object
 1   age      4 non-null      int64
 2   roll no  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

             age    roll no
count   4.000000   4.000000
mean   23.500000  38.500000
std     1.290994  14.200939
min    22.000000  22.000000
25%    22.750000  30.250000
50%    23.500000  38.500000
75%    24.250000  46.750000
max    25.000000  55.000000

In [ ]:
# 3 save and load data from csv

In [ ]:
df.to_csv('test_data.csv')

In [ ]:
load_df=pd.read_csv('test_data.csv')

In [ ]:
# 4 rows column selectin

In [ ]:
df[['name','age']]

     name  age
0  rajesh   22
1    ansh   23
2   suraj   24
3   ankit   25

In [ ]:
# select rows loc= lebel based indexing
df.loc[df.name=='rajesh']

     name  age  roll no
0  rajesh   22       22

In [ ]:
df.loc[df.name=='ansh']

   name  age  roll no
1  ansh   23       33

In [ ]:
df.loc[(df.name=='rajesh')&(df.age>=20)]

     name  age  roll no
0  rajesh   22       22

In [ ]:
# iloc index -value based
df.iloc[0]

name       rajesh
age            22
roll no        22
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]

     name  age  roll no
0  rajesh   22       22
1    ansh   23       33

In [ ]:
df['age']>20

0    True
1    True
2    True
3    True
Name: age, dtype: bool